### ISSUE TITLE
发现最新版（4.43）和AddOnSkins一同使用时不能移动图标的BUG

### ISSUE THREAD

**Issue by cycledm** [Witnesscm/WhisperPop#1]
插件版本：4.43

前置条件：安装ElvUI + AddOnSkins，并且在AddOnSkins的Skins中勾选WhisperPop

现象：对图标按住鼠标左键无法拖动。在AddOnSkins中取消勾选WhisperPop，或者直接禁用AddOnSkins，则恢复正常

备注：4.42及以下版本无此问题

**Comment by Witnesscm** [comment]
看了下是AddOnSkins对图标的美化导致了点击报错(OnMouseDown)，中断了后续的移动操作。有报错收集插件的话可以看到其他版本有同样的报错，是AddOnSkins的问题。

[4.44-alpha-1](https://github.com/Witnesscm/WhisperPop/releases/tag/4.44-alpha-1) 版本中恢复了之前的移动方法(OnDragStart)，需要注意的是AddOnSkins报错仍然存在
