### ISSUE TITLE
自定义消息字体大小和间距

### ISSUE THREAD

**Issue by dss886** [Witnesscm/WhisperPop#2]
我想把MessageFrame里面的字体调小一点，加一点间距，但是不知道为啥不生效。。

```
list:SetFont(NAMEPLATE_FONT, 12, "")
testFont:SetFont(NAMEPLATE_FONT, 12, "")
```
但是间距是没问题的
```
list.SetSpacing(MESSAGE_LINE_SPACING)
```
有点奇怪，而且也不报错。。有啥建议没

**Comment by Witnesscm** [comment]
list:SetFont(STANDARD_TEXT_FONT, 12, "")
SetFont第一个参数用字体路径，不要用字体对象

**Comment by dss886** [comment]
可以了！赞！
这几个变量有点坑...都是string类型，有的是路径，有的是对象名
