### ISSUE TITLE
游戏内点击按钮报错

### ISSUE THREAD

**Issue by coryshipit** [Witnesscm/WhisperPop#3]
游戏内点击按钮，弹出密语窗体的同时，报2个错误，具体如下：
1）
31x WhisperPop/Frames/Templates.lua:83: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: WhisperPopNotifyButtonIcon:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@WhisperPop/Frames/Templates.lua"]:83: in function <WhisperPop/Frames/Templates.lua:82>

Locals:
(*temporary) = WhisperPopNotifyButtonIcon {
 PixelSnapDisabled = true
}
(*temporary) = "CENTER"
(*temporary) = 1
(*temporary) = -1

2）
27x WhisperPop/Frames/Templates.lua:87: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: WhisperPopNotifyButtonIcon:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@WhisperPop/Frames/Templates.lua"]:87: in function <WhisperPop/Frames/Templates.lua:86>

Locals:
(*temporary) = WhisperPopNotifyButtonIcon {
 PixelSnapDisabled = true
}
(*temporary) = "CENTER"

**Comment by coryshipit** [comment]
使用的是最新的V4.45

**Comment by Witnesscm** [comment]
AddOnSkins美化导致的报错，和本插件无关 https://github.com/Witnesscm/WhisperPop/issues/1
